# Generated by Django 4.1 on 2022-09-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importancia',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
