# Generated by Django 4.1 on 2022-09-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'importancias',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('LISTADO', 'LISTADO'), ('POR_HACER', 'POR_HACER'), ('HACIENDO', 'HACIENDO'), ('FINALIZADO', 'FINALIZADO'), ('CANCELADO', 'CANCELADO')], default='LISTADO', max_length=15)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(null=True)),
                ('fechaCaducidad', models.DateTimeField(db_column='fecha_caducidad')),
                ('importancia', models.ForeignKey(db_column='importancia_id', on_delete=django.db.models.deletion.PROTECT, to='gestion.importancia')),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='TareaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(db_column='etiqueta_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.etiqueta')),
                ('tarea', models.ForeignKey(db_column='tarea_id', on_delete=django.db.models.deletion.CASCADE, to='gestion.tarea')),
            ],
            options={
                'db_table': 'tareas_etiquetas',
            },
        ),
    ]
