"""Crear tabla usuarios

Revision ID: 0856b473e91b
Revises: 50c60bcb184d
Create Date: 2022-08-25 20:43:36.572390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0856b473e91b'
down_revision = '50c60bcb184d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('usuarioNombre', sa.String(length=255), nullable=True),
    sa.Column('usuarioEmail', sa.String(length=255), nullable=False),
    sa.Column('usuarioDni', sa.String(length=8), nullable=True),
    sa.Column('usuarioFono', sa.String(length=50), nullable=True),
    sa.Column('usuarioHash', sa.Text(), nullable=True),
    sa.Column('usuarioSalt', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('usuarioId'),
    sa.UniqueConstraint('usuarioEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
