"""crear tabla preferencias

Revision ID: fb2844051e50
Revises: 04cabd9332d4
Create Date: 2022-08-19 22:02:40.568545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2844051e50'
down_revision = '04cabd9332d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencias',
    sa.Column('preferenciaId', sa.Integer(), nullable=False),
    sa.Column('preferenciaNombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('preferenciaId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferencias')
    # ### end Alembic commands ###
