# Generated by Django 4.1 on 2022-08-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productoId', models.AutoField(primary_key=True, serialize=False)),
                ('productoNombre', models.CharField(max_length=255)),
                ('productoDescripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
